---
title: >
  `\vspace{-48pt}`{=latex}**Meeting minutes**
fontsize: 12pt
geometry: margin=1in
linkcolor: black
urlcolor: black
output: 
  pdf_document
header-includes:
- \usepackage{setspace}
- \onehalfspacing
- \usepackage[nottoc]{tocbibind}
- \setlength{\parskip}{12pt}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, highlight=FALSE, message=FALSE, warning=FALSE)
```

\vspace{-36pt}
$\hrulefill$


# Team meeting on (Feb 06), 2026

## Location: (Zoom)

## Attendees: (All)

## Agenda:
1. Introduce two new members into the team
2. Dividing responsibilities for the first project feedback.

  

## Discussion summaries:
1.  The whole group read through the instructions and divided the responsibilities.
2.  Getting familiar with each other and exchange contacts.



## Key decisions (if not already included in discussion summaries):


## Action items (if not already included in discussion summaries):
-  Alex writes the basic introduction and why is it concerning.
-  Samuya writes what factors should be considered.
-  Freya writes transisions to the rest of the report including our objectives, variables and methodologies.
-  Yuhan works on the references.
-  Ruixin does proof reading


$\hrulefill$



